### ISSUE TITLE
[question] Why Do We Have To Keep The Tab Open?

### ISSUE THREAD

**Issue by CmdrNorthpaw** [WorldLanguages/ScratchMsgNotifier#10]
Why do we have to keep scratchnotifier.cf open for notifications? YouTube still notifies you if it's closed.
OctoPenguin

**Comment by WorldLanguages** [comment]
Youtube (and also Scratch Notifier for Android) use service workers and check in their servers for you if they need to notify you.

I'll probably make a new notifier version that works like the mobile one soon so you don't need to keep the tab open.
