### ISSUE TITLE
User control over backgrounds?

### ISSUE THREAD

**Issue by NilsTheBest** [WorldLanguages/ScratchMsgNotifier#11]
I'd like to suggest that, perhaps the user could have control over the backgrounds. In other words, there could conceivably be a menu in "settings" in which among every other already existing background, a background in particular can be chosen and changed at anytime that one wishes to.

**Comment by NilsTheBest** [comment]
To make it so that the background is the same when the user comes back on scratchnotifier, would implementing cookies be possible?

**Comment by MasterOfTheTiger** [comment]
You'd use localStorage.
