### ISSUE TITLE
Are you open to people forking this repo simply to redesign the look of the page?

### ISSUE THREAD

**Issue by ethanhanderson** [WorldLanguages/ScratchMsgNotifier#12]
The site's design is poorly put together in my opinion, and I'd be willing to help out and redesign the page to make it easier to navigate and to make a statement of the work you've put into it if you're okay with me doing so.

Thanks,
@Hexsphere

**Comment by MasterOfTheTiger** [comment]
It is actually illegal to do so without his permission because there is no license. Thus this project is not actually open source.

**Comment by ethanhanderson** [comment]
Very good point. Hence all the better to ask. :)

**Comment by MasterOfTheTiger** [comment]
@Hexsphere You should check out #1.

**Comment by ethanhanderson** [comment]
I did, and that seems to show I would be able to without asking, but all I aimed to do was inquire if I could make some design changes. 😄

**Comment by MasterOfTheTiger** [comment]
He likely will not merge them. It is best to get permission to fork the project and make your own version. He already gave me permission to do so, but I haven't had time to do so.

**Comment by ethanhanderson** [comment]
Ohh, okay. Thanks for the help. ;)

**Comment by MasterOfTheTiger** [comment]
Yeah, both the person that opened #1 and myself have opened pull requests and they were "Merged locally" (not really).

**Comment by ethanhanderson** [comment]
Noted.
