### ISSUE TITLE
"The username you entered doesn't exist. Press OK and try again." on every account

### ISSUE THREAD

**Issue by MasterOfTheTiger** [WorldLanguages/ScratchMsgNotifier#15]
Any account name I try to enter it gives the error message "The username you entered doesn't exist. Press OK and try again." even when they do exist.

**Comment by WorldLanguages** [comment]
The Scratch API for some reason is now missing the "Access-Control-Allow-Origin" response header.
Because of that, ScratchNotifier can't access message counts or check if usernames exist...
