### ISSUE TITLE
"close notifications after x seconds" isn't clear

### ISSUE THREAD

**Issue by NilsTheBest** [WorldLanguages/ScratchMsgNotifier#16]
When going in "settings", we can't see the amount of seconds the notifications close after:
http://u.cubeupload.com/NilsTheBest77/CantSee.png
Maybe the arrows could be a bit further away from the number?

**Comment by WorldLanguages** [comment]
Thanks for submitting the issue! I won't fix this atm, but will take this into account for Scratch Notifier v3
