### ISSUE TITLE
Taking into account banned users

### ISSUE THREAD

**Issue by moeenio** [WorldLanguages/ScratchMsgNotifier#17]
I am temporarily banned from Scratch, and the notifier loads without problem and shows me my message count, but my profile pic doesn't load (since it redirects the image request to the banned account page). Maybe make an error message and don't load the notifier if the user is banned ?

**Comment by WorldLanguages** [comment]
Because of web security limitations websites can't know if your Scratch account is banned.

**Comment by moeenio** [comment]
Maybe you can do a request to the user profile page, and if it redirects to the banned page, then don't load notifer/ show message
