### ISSUE TITLE
Popup for "Notes"

### ISSUE THREAD

**Issue by MasterOfTheTiger** [WorldLanguages/ScratchMsgNotifier#2]
Instead of opening the notes in a constantly loading new tab, I think it would be neat to have it pop-up and have the close button close the popup.

**Comment by MasterOfTheTiger** [comment]
I would be willing to give it a try (I really would like to submit my own code for another project sometime).

**Comment by WorldLanguages** [comment]
I honestly like it this way.

I don't see notes as part of the website interface itself - it's boring, legal things I have to tell my users. That's why I open it in a new tab. It's different from the other clickable things from the website.

**Comment by MasterOfTheTiger** [comment]
Oh, okay. I will keep looking for things I can help with.

**Comment by WorldLanguages** [comment]
If you'd like you can make the popup for the settings (not swal, an actual popup) and then I'll add the options! :)

**Comment by MasterOfTheTiger** [comment]
1. What is swal? [Figured out]
2. How do you want me to make it? What exactly do I need to add for you to add the settings on?

**Comment by WorldLanguages** [comment]
dont worry I'll do it myself I've got the time now :p

**Comment by MasterOfTheTiger** [comment]
Okay. Sorry. This is what I have come up with so far: 
![screenshot at 2018-02-09 12-14-41](https://user-images.githubusercontent.com/16640496/36048089-e73e4ef2-0d92-11e8-98a7-d157768ea2a5.png)

**Comment by WorldLanguages** [comment]
oh nice, is that an image or is it coded?

**Comment by MasterOfTheTiger** [comment]
I coded that and then took a screenshot. Wait a sec, I am going to push my changes to my fork.

**Comment by WorldLanguages** [comment]
Pull a request pls!

**Comment by MasterOfTheTiger** [comment]
I did.

**Comment by WorldLanguages** [comment]
Settings are live :)
