### ISSUE TITLE
Anti-collaboration

### ISSUE THREAD

**Issue by MasterOfTheTiger** [WorldLanguages/ScratchMsgNotifier#6]
You seem to be anti-collaboration with the way you manage this project. You "work with your pull requests locally" (or maybe not at all), which gives you credit for others' work (if you even include any of it), you do not have a license for it, which means no one else can legally use your program for their own uses (thus it is not open source), and you make most of your commits with "." or sometimes you do something allong the lines of, "whoops". You need to be more friendly to collaborators, and anyone else that wants to look at and maybe use your code. Also, you do not have information about the program in the README, or even something about collaboration documented anywhere.

**Comment by WorldLanguages** [comment]
Hi, sorry if you see this repo that way. 

I made this website as a goal of building a site by myself, or at least mostly. But that doesn't mean I don't want people collaborating on this notifier.
The fact that this doesn't have a license, that I don't explain commits, or don't have a "beautiful" repo does not mean I don't want collaboration. I simply work that way if I'm working on a site mostly myself. I know not everybody works that way. But I do not consider these important. 
If somebody wants clarification or wants to contribute, I'd say sure, but I'm not interested, at least on this project, to incentivise people to collaborate - this site is pretty much done, no more features to add.

**Comment by MasterOfTheTiger** [comment]
@WorldLanguages Can you please add a license to this repo? It would be very helpful as it explains how this is allowed to be distributed. Thank you.

**Comment by WorldLanguages** [comment]
I don't feel I know enough about licenses right now to choose one. I don't even know what I would like to allow people doing with this code... honestly

**Comment by WorldLanguages** [comment]
Did something in special make you say this, or was it just random? Maybe I can fix that

**Comment by MasterOfTheTiger** [comment]
@WorldLanguages I mean I want to be able to study your code and use it to further my own projects, but currently I cannot do that. Also, it is important in general for every open source project to be licensed. 


What caused this is simply I was following the repo and kept seeing ".". Not to say that I do everything right or to put myself above you in any way (you are amazing with programming in general), but even my projects that I work with privately (but are hosted on GitHub) have some documentation and I put basic detail into commits.

**Comment by MasterOfTheTiger** [comment]
> I don't feel I know enough about licenses right now to choose one. I don't even know what I would like to allow people doing with this code... honestly

MIT is permissive and allows people to do pretty much whatever with it as long as they give you credit and don't sue you.

GPL allows people to change the code and distribute it as long as they give you credit, don't sue you, and keep the same license (or in some cases a similar one). 

Apache is like MIT but with a much more words, and it deals with patents.

More information can be found at https://choosealicense.com/

**Comment by WorldLanguages** [comment]
Right I'll try to organize my GitHub repos from now on :P Thanks for your feedback

**Comment by MasterOfTheTiger** [comment]
I was being kinda harsh and uncaring with my words. I apologize.

**Comment by WorldLanguages** [comment]
Nah no worries I instantly noticed you were not in a normal mood :P

**Comment by MasterOfTheTiger** [comment]
Thanks for understanding. :)
