### ISSUE TITLE
Desktop Program

### ISSUE THREAD

**Issue by MasterOfTheTiger** [WorldLanguages/ScratchMsgNotifier#7]
I want to experiment with my skills and make a desktop program for this. Can I do it? It would be an independent project rooted in this one.

**Comment by WorldLanguages** [comment]
Sure! You won't be able to share it on Scratch, but do it if you want lol

**Comment by MasterOfTheTiger** [comment]
What are the rules for doing it? What license I mean.

**Comment by WorldLanguages** [comment]
Sorry, missed that comment. Do whatever you want with the code. If you force me to choose a license, MIT license.

**Comment by MasterOfTheTiger** [comment]
Okay. I just want to know what the legal restrictions there are with it. I am going to behold an Electron app based on your code. It is going to look very different and it is not going to mine. It will be redesigned for an app

**Comment by WorldLanguages** [comment]
Ohh, so that's what Discord and GH Pages are made of??? Ayy I was searching what was used to build apps in JS.

No legal restrictions. I'd use it but I just hate native Windows notifications. Good luck!

**Comment by WorldLanguages** [comment]
Feel free to remove the ad or mining btw
